services:
  server:
    build: ./server
    restart: on-failure
  nginx: 
    image: nginx:stable-alpine3.19-slim
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure
    depends_on:
      - server
    ports:
      - "45276:80"